# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PKNY
tagline:             'Blah blah blah yeah!'
description:         "Just another bunch of word salads server up on the Internet's kitchen table..."
url:                 http://lanyon.getpoole.com
baseurl:             'http://pkny.github.io/'
paginate:            5

# About/contact
author:
  name:              Paul Klump
  url:               https://twitter.com/p_k_n_y
  email:             blah@blah.com

# Custom vars
version:             1.0.0
