# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PKNY
tagline:             Blah Blah Blah Yeah!
description:         'Just another bunch of word salads served up on the Internet's kitchen table...'
url:                 http://lanyon.getpoole.com
baseurl:             'http://pkny.github.io'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
